kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volume-rw-many-web
  labels:
    type: local-web
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/data-rw-many"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volume-rw-once-db
  labels:
    type: local-db
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data-rw-once"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-prm-pv-claim
  labels:
    app: web
spec:
  selector:
    matchLabels:
      type: local-web
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-prm-pv-claim
  labels:
    app: db-primary
spec:
  selector:
    matchLabels:
      type: local-db
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi